apiVersion: apps/v1
kind: Deployment
metadata:
  name: copilot-hindi-demo
  labels:
    app: copilot-hindi-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: copilot-hindi-demo
  template:
    metadata:
      labels:
        app: copilot-hindi-demo
    spec:
      containers:
      - name: copilot-hindi-demo
        image: siddjoshi/copilot-hindi-demo:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: copilot-hindi-demo-service
spec:
  selector:
    app: copilot-hindi-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer